# Generated by Django 4.2.9 on 2024-02-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Borrowing",
        ),
    ]
